---
apiVersion: v1
kind: Namespace
metadata:
  name: ibm-ucd
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: username-pwd
  namespace: ibm-ucd
data:
  mongodb_username: devdb
  #mongodb_password: devdb@123
  #Testing using secretKeyRef test configMa
# bash-3.2$ echo -n 'devdb@123' | base64
# ZGV2ZGJAMTIz
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-pwd
  namespace: ibm-ucd
type: Opaque
stringData:
  mongodb_password: devdb@123
